pipeline {
  agent any

  tools {
    dockerTool 'docker'
  }

  stages {
    stage('Build Backend') {
      steps {
        script {
          dir('pitterpatter') {
            sh 'docker build -t pitterpatter-backend .'
          }
        }
      }
    }
  }
}
